"""Initial migration for seats and occupancy

Revision ID: d371fdde0ef3
Revises: 
Create Date: 2026-05-03 09:16:34.924769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd371fdde0ef3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coordinate_x', sa.Integer(), nullable=False),
    sa.Column('coordinate_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupancy_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupancy_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('current_state', sa.Enum('AVAILABLE', 'OCCUPIED', 'AWAY', name='occupancystate'), nullable=False),
    sa.Column('last_state_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occupancy_status')
    op.drop_table('occupancy_analytics')
    op.drop_table('seats')
    # ### end Alembic commands ###
