"""Add OccupancyState enum and apply to occupancy_status

Revision ID: ed65192d90d1
Revises: d371fdde0ef3
Create Date: 2026-05-03 11:40:32.222186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed65192d90d1'
down_revision: Union[str, Sequence[str], None] = 'd371fdde0ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
